import NavMenu from "@/components/NavMenu";
import "./globals.css";

export const metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default function RootLayout({ children }) {
	return (
		<html lang="en">
			<body style={{ padding: "1rem" }}>
				<NavMenu />

				<div style={{ padding: "1rem" }}>{children}</div>
			</body>
		</html>
	);
}
